pretrained:
  model: google/bert_uncased_L-2_H-128_A-2
  tokenizer: google/bert_uncased_L-2_H-128_A-2
output_classes: 2
trained:
  model_uri: runs:/815c8882c08f44d0a64a172b1f52a040/classification_model
