pretrained:
  model: google/bert_uncased_L-2_H-128_A-2
  tokenizer: google/bert_uncased_L-2_H-128_A-2
output_classes: 2
trained:
  model_uri: runs:/568142ea50184562b5a60bc9f806fd24/classification_model
