global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'operational-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:5000']
  - job_name: 'ml-metrics'
    static_configs:
      - targets: ['localhost:5001']

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']
